"""initial schema

Revision ID: 3d83000cfb73
Revises: 
Create Date: 2026-09-29 21:52:37.016037

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3d83000cfb73'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto")
    op.execute("CREATE SEQUENCE IF NOT EXISTS fraud_case_seq START 1")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer',
    sa.Column('customer_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('bvn_hash', sa.String(length=64), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('phone_hash', sa.String(length=64), nullable=False),
    sa.Column('phone_last4', sa.String(length=4), nullable=False),
    sa.Column('date_joined', sa.Date(), nullable=False),
    sa.Column('risk_profile', sa.String(length=10), server_default=sa.text("'low'"), nullable=False),
    sa.PrimaryKeyConstraint('customer_id')
    )
    op.create_table('model_version',
    sa.Column('model_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('algorithm', sa.String(length=30), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('path', sa.String(length=255), nullable=False),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('deployed_on', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.PrimaryKeyConstraint('model_id'),
    sa.UniqueConstraint('version')
    )
    op.create_table('role',
    sa.Column('role_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('permissions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('role_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('system_setting',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_by', sa.String(length=150), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('account',
    sa.Column('account_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('account_number', sa.String(length=10), nullable=False),
    sa.Column('account_type', sa.String(length=10), nullable=False),
    sa.Column('opened_on', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=10), server_default=sa.text("'ACTIVE'"), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.customer_id'], ),
    sa.PrimaryKeyConstraint('account_id'),
    sa.UniqueConstraint('account_number')
    )
    op.create_table('app_user',
    sa.Column('user_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password_hash', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.role_id'], ),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('audit_log',
    sa.Column('log_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('actor', sa.String(length=50), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('entity', sa.String(length=30), nullable=False),
    sa.Column('entity_id', sa.String(length=40), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.user_id'], ),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_index('ix_audit_log_entity', 'audit_log', ['entity', 'entity_id'], unique=False)
    op.create_index('ix_audit_log_timestamp', 'audit_log', ['timestamp'], unique=False)
    op.create_table('notification',
    sa.Column('notification_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=False),
    sa.Column('link', sa.String(length=300), nullable=True),
    sa.Column('is_read', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.user_id'], ),
    sa.PrimaryKeyConstraint('notification_id')
    )
    op.create_table('security_event',
    sa.Column('event_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=30), nullable=False),
    sa.Column('event_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.account_id'], ),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index('ix_security_event_account_time', 'security_event', ['account_id', 'event_time'], unique=False)
    op.create_table('txn',
    sa.Column('txn_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('txn_ref', sa.String(length=40), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('txn_type', sa.String(length=20), nullable=False),
    sa.Column('txn_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('beneficiary_account', sa.String(length=20), nullable=True),
    sa.Column('beneficiary_bank', sa.String(length=10), nullable=True),
    sa.Column('device_id', sa.String(length=64), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=False),
    sa.Column('balance_before', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.account_id'], ),
    sa.PrimaryKeyConstraint('txn_id'),
    sa.UniqueConstraint('txn_ref')
    )
    op.create_index('ix_txn_account_beneficiary', 'txn', ['account_id', 'beneficiary_account'], unique=False)
    op.create_index('ix_txn_account_device', 'txn', ['account_id', 'device_id'], unique=False)
    op.create_index('ix_txn_account_time', 'txn', ['account_id', 'txn_time'], unique=False)
    op.create_index('ix_txn_created_at', 'txn', ['created_at'], unique=False)
    op.create_index('ix_txn_status', 'txn', ['status'], unique=False)
    op.create_table('prediction',
    sa.Column('prediction_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('txn_id', sa.UUID(), nullable=False),
    sa.Column('model_id', sa.UUID(), nullable=False),
    sa.Column('fraud_score', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('risk_band', sa.String(length=10), nullable=False),
    sa.Column('shap_values', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('features', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('latency_ms', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['model_version.model_id'], ),
    sa.ForeignKeyConstraint(['txn_id'], ['txn.txn_id'], ),
    sa.PrimaryKeyConstraint('prediction_id'),
    sa.UniqueConstraint('txn_id')
    )
    op.create_index('ix_prediction_band_created', 'prediction', ['risk_band', 'created_at'], unique=False)
    op.create_table('alert',
    sa.Column('alert_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('prediction_id', sa.UUID(), nullable=False),
    sa.Column('severity', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dismiss_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['prediction_id'], ['prediction.prediction_id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['app_user.user_id'], ),
    sa.PrimaryKeyConstraint('alert_id'),
    sa.UniqueConstraint('prediction_id')
    )
    op.create_index('ix_alert_status_created', 'alert', ['status', 'created_at'], unique=False)
    op.create_table('fraud_case',
    sa.Column('case_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('case_number', sa.String(length=20), nullable=False),
    sa.Column('alert_id', sa.UUID(), nullable=True),
    sa.Column('txn_id', sa.UUID(), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('assigned_to', sa.UUID(), nullable=True),
    sa.Column('priority', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=25), nullable=False),
    sa.Column('outcome', sa.String(length=25), nullable=True),
    sa.Column('fraud_type', sa.String(length=30), nullable=True),
    sa.Column('amount_at_risk', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('amount_recovered', sa.Numeric(precision=15, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('ack_due_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolve_due_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['alert_id'], ['alert.alert_id'], ),
    sa.ForeignKeyConstraint(['assigned_to'], ['app_user.user_id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['app_user.user_id'], ),
    sa.ForeignKeyConstraint(['txn_id'], ['txn.txn_id'], ),
    sa.PrimaryKeyConstraint('case_id'),
    sa.UniqueConstraint('case_number')
    )
    op.create_index('ix_fraud_case_assigned_status', 'fraud_case', ['assigned_to', 'status'], unique=False)
    op.create_index('ix_fraud_case_resolve_due', 'fraud_case', ['resolve_due_at'], unique=False)
    op.create_index('ix_fraud_case_status_priority', 'fraud_case', ['status', 'priority'], unique=False)
    op.create_table('case_attachment',
    sa.Column('attachment_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('uploaded_by', sa.UUID(), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('storage_path', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['fraud_case.case_id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['app_user.user_id'], ),
    sa.PrimaryKeyConstraint('attachment_id')
    )
    op.create_table('case_note',
    sa.Column('note_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('note_type', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['fraud_case.case_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.user_id'], ),
    sa.PrimaryKeyConstraint('note_id')
    )
    # ### end Alembic commands ###

    # Section 7.3: exactly one model_version row may be active.
    op.execute(
        "CREATE UNIQUE INDEX ix_model_version_one_active "
        "ON model_version (is_active) WHERE is_active"
    )

    # Section 7.1: audit_log is append-only. docker-compose runs migrations
    # and the app under the same single Postgres role (docs/DECISIONS.md
    # D18), so a plain REVOKE on that role is a no-op (table owners bypass
    # grant checks in Postgres). A BEFORE UPDATE/DELETE trigger enforces it
    # for every role, including the owner, which is the stronger guarantee
    # the spec is really asking for.
    op.execute(
        """
        CREATE OR REPLACE FUNCTION audit_log_append_only() RETURNS trigger AS $$
        BEGIN
            RAISE EXCEPTION 'audit_log is append-only: % not permitted', TG_OP;
        END;
        $$ LANGUAGE plpgsql;
        """
    )
    op.execute(
        """
        CREATE TRIGGER audit_log_no_update_delete
        BEFORE UPDATE OR DELETE ON audit_log
        FOR EACH ROW EXECUTE FUNCTION audit_log_append_only();
        """
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP SEQUENCE IF EXISTS fraud_case_seq")
    op.execute("DROP TRIGGER IF EXISTS audit_log_no_update_delete ON audit_log")
    op.execute("DROP FUNCTION IF EXISTS audit_log_append_only()")
    op.execute("DROP INDEX IF EXISTS ix_model_version_one_active")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('case_note')
    op.drop_table('case_attachment')
    op.drop_index('ix_fraud_case_status_priority', table_name='fraud_case')
    op.drop_index('ix_fraud_case_resolve_due', table_name='fraud_case')
    op.drop_index('ix_fraud_case_assigned_status', table_name='fraud_case')
    op.drop_table('fraud_case')
    op.drop_index('ix_alert_status_created', table_name='alert')
    op.drop_table('alert')
    op.drop_index('ix_prediction_band_created', table_name='prediction')
    op.drop_table('prediction')
    op.drop_index('ix_txn_status', table_name='txn')
    op.drop_index('ix_txn_created_at', table_name='txn')
    op.drop_index('ix_txn_account_time', table_name='txn')
    op.drop_index('ix_txn_account_device', table_name='txn')
    op.drop_index('ix_txn_account_beneficiary', table_name='txn')
    op.drop_table('txn')
    op.drop_index('ix_security_event_account_time', table_name='security_event')
    op.drop_table('security_event')
    op.drop_table('notification')
    op.drop_index('ix_audit_log_timestamp', table_name='audit_log')
    op.drop_index('ix_audit_log_entity', table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_table('app_user')
    op.drop_table('account')
    op.drop_table('system_setting')
    op.drop_table('role')
    op.drop_table('model_version')
    op.drop_table('customer')
    # ### end Alembic commands ###
